### ISSUE TITLE
Wyjścia w zap1.out i zap2.out

### ISSUE THREAD

**Issue by Lecorbio** [kartof0nix/testy-zap#2]
Czemu nie ma wyjść do zap1.out i zap2.out?

**Comment by kartof0nix** [comment]
Czy możesz dokładniej opisać problem? Pliki zap1.out i zap2.out są wyjściami, w których każda linijka odpowiada kolejnemu testowi.

**Comment by kartof0nix** [comment]
Być może rzeczywiście nie najlepiej sprecyzowałem jak działa ta testerka, odsyłam więc do pierwszej sekcji pliku README.md
